import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Headphones, ShieldCheck, Sparkles, Truck } from 'lucide-react'
import ProductCard from '../components/ProductCard'
import { getProducts } from '../services/products'
import '../styles/home.css'
export default function Home(){const [products,setProducts]=useState([]);useEffect(()=>{getProducts().then(setProducts)},[]);return <main>
 {/* Banner principal */}<section className="hero"><img src="/images/hero-ej.png" alt="Seleção premium EJ Importados"/><div className="container hero-content"><h1>O extraordinário,<br/>agora ao seu alcance.</h1><p>Perfumes marcantes, beleza e tecnologia escolhidos para elevar sua rotina.</p><Link className="primary-button" to="/ofertas">Explorar novidades <ArrowRight size={18}/></Link></div></section>
 {/* Categorias */}<section className="container section"><div className="section-title"><div><span>ESCOLHA SEU UNIVERSO</span><h2>Categorias em destaque</h2></div></div><div className="category-grid"><Link to="/perfumaria" className="category perfume"><b>Perfumaria</b><span>Árabes, importados e nacionais</span></Link><Link to="/eletronicos" className="category tech"><b>Eletrônicos</b><span>Tecnologia para todos os momentos</span></Link><Link to="/cosmeticos" className="category beauty"><b>Beleza</b><span>Seu ritual, do seu jeito</span></Link><Link to="/acessorios" className="category access"><b>Acessórios</b><span>Detalhes que fazem diferença</span></Link></div></section>
 {/* Produtos */}<section className="product-section"><div className="container section"><div className="section-title"><div><span>PREÇOS ESPECIAIS</span><h2>Os queridinhos da semana</h2></div><Link to="/ofertas">Ver todos <ArrowRight size={16}/></Link></div><div className="products-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
 {/* Campanha */}<section className="container editorial"><div><span>PERFUMES COM PRESENÇA</span><h2>Encontre uma fragrância que conte a sua história.</h2><p>Uma seleção de aromas envolventes, dos florais luminosos aos amadeirados intensos.</p><Link to="/perfumaria">Descobrir fragrâncias <ArrowRight size={17}/></Link></div></section>
 {/* Novidades */}<section className="container section"><div className="section-title"><div><span>ACABOU DE CHEGAR</span><h2>Novidades na EJ</h2></div></div><div className="products-grid">{products.slice(4,8).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
 {/* Benefícios */}<section className="benefits"><div className="container"><div><Truck/><span><b>Entrega para todo Brasil</b><small>Acompanhe cada etapa</small></span></div><div><ShieldCheck/><span><b>Compra 100% segura</b><small>Seus dados protegidos</small></span></div><div><Sparkles/><span><b>Produtos selecionados</b><small>Qualidade e procedência</small></span></div><div><Headphones/><span><b>Atendimento humano</b><small>Estamos perto de você</small></span></div></div></section>
 </main>}
